version: "2"
run:
  allow-parallel-runners: true
linters:
  default: all
  disable:
    - cyclop
    - depguard
    - exhaustruct
    - funlen
    - gochecknoglobals
    - gocognit
    - inamedparam
    - ireturn
    - lll
    - maintidx
    - mnd
    - nlreturn
    - nonamedreturns
    - protogetter
    - testpackage
    - varnamelen
    - wrapcheck
    - wsl
  settings:
    errcheck:
      check-type-assertions: true
    forbidigo:
      forbid:
        - pattern: ^fmt\.Print
        - pattern: ^log\.
        - pattern: ^print$
        - pattern: ^println$
        - pattern: ^panic$
    godox:
      keywords:
        - FIXME
    importas:
      no-unaliased: true
    varnamelen:
      ignore-decls:
        - T any
        - i int
        - wg sync.WaitGroup
  exclusions:
    generated: lax
    presets:
      - comments
      - common-false-positives
      - legacy
      - std-error-handling
    rules:
      - path: (.+)\.go$
        text: 'do not define dynamic errors, use wrapped static errors instead: .*'
    paths:
      - protogen
issues:
  max-same-issues: 0
formatters:
  enable:
    - gci
    - gofmt
    - gofumpt
  settings:
    gci:
      sections:
        - standard
        - default
        - localmodule
  exclusions:
    generated: lax
    paths:
      - protogen
